artifact_uri: file:///C:/Users/naras/Work/WILP/MLOPS/Assignment1/HeartDiseasePredictor/mlruns/608454654416338805/302fa443c29742d19d05a0d0f7fc0afd/artifacts
end_time: 1783725226574
entry_point_name: ''
experiment_id: '608454654416338805'
lifecycle_stage: active
run_id: 302fa443c29742d19d05a0d0f7fc0afd
run_name: Candidate Model
source_name: ''
source_type: 4
source_version: ''
start_time: 1783725216554
status: 3
tags: []
user_id: naras
